export const stateList = [
  { value: '1', label: 'San José' },
  { value: '2', label: 'Alajuela' },
  { value: '3', label: 'Cartago' },
  { value: '4', label: 'Heredia' },
  { value: '5', label: 'Guanacaste' },
  { value: '6', label: 'Puntarenas' },
  { value: '7', label: 'Limón' },
]

export const cityMap = {
  '1': [
    { value: '01', label: 'San José' },
    { value: '02', label: 'Escazú' },
    { value: '03', label: 'Desamparados' },
    { value: '04', label: 'Puriscal' },
    { value: '05', label: 'Tarrazú' },
    { value: '06', label: 'Aserrí' },
    { value: '07', label: 'Mora' },
    { value: '08', label: 'Goicoechea' },
    { value: '09', label: 'Santa Ana' },
    { value: '10', label: 'Alajuelita' },
    { value: '11', label: 'Vázquez de Coronado' },
    { value: '12', label: 'Acosta' },
    { value: '13', label: 'Tibás' },
    { value: '14', label: 'Moravia' },
    { value: '15', label: 'Montes de Oca' },
    { value: '16', label: 'Turrubares' },
    { value: '17', label: 'Dota' },
    { value: '18', label: 'Curridabat' },
    { value: '19', label: 'Pérez Zeledón' },
    { value: '20', label: 'León Cortés Castro' },
  ],
  '2': [
    { value: '01', label: 'Alajuela' },
    { value: '02', label: 'San Ramón' },
    { value: '03', label: 'Grecia' },
    { value: '04', label: 'San Mateo' },
    { value: '05', label: 'Atenas' },
    { value: '06', label: 'Naranjo' },
    { value: '07', label: 'Palmares' },
    { value: '08', label: 'Poás' },
    { value: '09', label: 'Orotina' },
    { value: '10', label: 'San Carlos' },
    { value: '11', label: 'Zarcero' },
    { value: '12', label: 'Sarchí' },
    { value: '13', label: 'Upala' },
    { value: '14', label: 'Los Chiles' },
    { value: '15', label: 'Guatuso' },
    { value: '16', label: 'Río Cuarto' },
  ],
  '3': [
    { value: '01', label: 'Cartago' },
    { value: '02', label: 'Paraíso' },
    { value: '03', label: 'La Unión' },
    { value: '04', label: 'Jiménez' },
    { value: '05', label: 'Turrialba' },
    { value: '06', label: 'Alvarado' },
    { value: '07', label: 'Oreamuno' },
    { value: '08', label: 'El Guarco' },
  ],
  '4': [
    { value: '01', label: 'Heredia' },
    { value: '02', label: 'Barva' },
    { value: '03', label: 'Santo Domingo' },
    { value: '04', label: 'Santa Bárbara' },
    { value: '05', label: 'San Rafael' },
    { value: '06', label: 'San Isidro' },
    { value: '07', label: 'Belén' },
    { value: '08', label: 'Flores' },
    { value: '09', label: 'San Pablo' },
    { value: '10', label: 'Sarapiquí' },
  ],

  '5': [
    { value: '01', label: 'Liberia' },
    { value: '02', label: 'Nicoya' },
    { value: '03', label: 'Santa Cruz' },
    { value: '04', label: 'Bagaces' },
    { value: '05', label: 'Carrillo' },
    { value: '06', label: 'Cañas' },
    { value: '07', label: 'Abangares' },
    { value: '08', label: 'Tilarán' },
    { value: '09', label: 'Nandayure' },
    { value: '10', label: 'La Cruz' },
    { value: '11', label: 'Hojancha' },
  ],

  '6': [
    { value: '01', label: 'Puntarenas' },
    { value: '02', label: 'Esparza' },
    { value: '03', label: 'Buenos Aires' },
    { value: '04', label: 'Montes de Oro' },
    { value: '05', label: 'Osa' },
    { value: '06', label: 'Quepos' },
    { value: '07', label: 'Golfito' },
    { value: '08', label: 'Coto Brus' },
    { value: '09', label: 'Parrita' },
    { value: '10', label: 'Corredores' },
    { value: '11', label: 'Garabito' },
  ],

  '7': [
    { value: '01', label: 'Limón' },
    { value: '02', label: 'Pococí' },
    { value: '03', label: 'Siquirres' },
    { value: '04', label: 'Talamanca' },
    { value: '05', label: 'Matina' },
    { value: '06', label: 'Guácimo' },
  ],
}

export const countyMap = {
  // SAN JOSE
  '101': [
    { value: '01', label: 'Carmen' },
    { value: '02', label: 'Merced' },
    { value: '03', label: 'Hospital' },
    { value: '04', label: 'Catedral' },
    { value: '05', label: 'Zapote' },
    { value: '06', label: 'San Francisco de Dos Ríos' },
    { value: '07', label: 'Uruca' },
    { value: '08', label: 'Mata Redonda' },
    { value: '09', label: 'Pavas' },
    { value: '10', label: 'Hatillo' },
    { value: '11', label: 'San Sebastián' },
  ],
  '102': [
    { value: '01', label: 'Escazú' },
    { value: '02', label: 'San Antonio' },
    { value: '03', label: 'San Rafael' },
  ],
  '103': [
    { value: '01', label: 'Desamparados' },
    { value: '02', label: 'San Miguel' },
    { value: '03', label: 'San Juan de Dios' },
    { value: '04', label: 'San Rafael Arriba' },
    { value: '05', label: 'San Antonio' },
    { value: '06', label: 'Frailes' },
    { value: '07', label: 'Patarrá' },
    { value: '08', label: 'San Cristóbal' },
    { value: '09', label: 'Rosario' },
    { value: '10', label: 'Damas' },
    { value: '11', label: 'San Rafael Abajo' },
    { value: '12', label: 'Gravilias' },
    { value: '13', label: 'Los Guido' },
  ],
  '104': [
    { value: '01', label: 'Santiago' },
    { value: '02', label: 'Mercedes Sur' },
    { value: '03', label: 'Barbacoas' },
    { value: '04', label: 'Grifo Alto' },
    { value: '05', label: 'San Rafael' },
    { value: '06', label: 'Candelarita' },
    { value: '07', label: 'Desamparaditos' },
    { value: '08', label: 'San Antonio' },
    { value: '09', label: 'Chires' },
  ],
  '105': [
    { value: '01', label: 'San Marcos' },
    { value: '02', label: 'San Lorenzo' },
    { value: '03', label: 'San Carlos' },
  ],
  '106': [
    { value: '01', label: 'Aserrí' },
    { value: '02', label: 'Tarbaca' },
    { value: '03', label: 'Vuelta de Jorco' },
    { value: '04', label: 'San Gabriel' },
    { value: '05', label: 'Legua' },
    { value: '06', label: 'Monterrey' },
    { value: '07', label: 'Salitrillos' },
  ],
  '107': [
    { value: '01', label: 'Colón' },
    { value: '02', label: 'Guayabo' },
    { value: '03', label: 'Tabarcia' },
    { value: '04', label: 'Piedras Negras' },
    { value: '05', label: 'Picagres' },
    { value: '06', label: 'Jaris' },
    { value: '07', label: 'Quitirrisí' },
  ],
  '108': [
    { value: '01', label: 'Guadalupe' },
    { value: '02', label: 'San Francisco' },
    { value: '03', label: 'Calle Blancos' },
    { value: '04', label: 'Mata de Plátano' },
    { value: '05', label: 'Ipís' },
    { value: '06', label: 'Rancho Redondo' },
    { value: '07', label: 'Purral' },
  ],
  '109': [
    { value: '01', label: 'Santa Ana' },
    { value: '02', label: 'Salitral' },
    { value: '03', label: 'Pozos' },
    { value: '04', label: 'Uruca' },
    { value: '05', label: 'Piedades' },
    { value: '06', label: 'Brasil' },
  ],
  '110': [
    { value: '01', label: 'Alajuelita' },
    { value: '02', label: 'San Josecito' },
    { value: '03', label: 'San Antonio' },
    { value: '04', label: 'Concepción' },
    { value: '05', label: 'San Felipe' },
  ],
  '111': [
    { value: '01', label: 'San Isidro' },
    { value: '02', label: 'San Rafael' },
    { value: '03', label: 'Dulce Nombre de Jesús' },
    { value: '04', label: 'Patalillo' },
    { value: '05', label: 'Cascajal' },
  ],
  '112': [
    { value: '01', label: 'San Ignacio' },
    { value: '02', label: 'Guaitil' },
    { value: '03', label: 'Palmichal' },
    { value: '04', label: 'Cangrejal' },
    { value: '05', label: 'Sabanillas' },
  ],
  '113': [
    { value: '01', label: 'San Juan' },
    { value: '02', label: 'Cinco Esquinas' },
    { value: '03', label: 'Anselmo Llorente' },
    { value: '04', label: 'León XIII' },
    { value: '05', label: 'Colima' },
  ],
  '114': [
    { value: '01', label: 'San Vicente' },
    { value: '02', label: 'San Jerónimo' },
    { value: '03', label: 'La Trinidad' },
  ],
  '115': [
    { value: '01', label: 'San Pedro' },
    { value: '02', label: 'Sabanilla' },
    { value: '03', label: 'Mercedes' },
    { value: '04', label: 'San Rafael' },
  ],
  '116': [
    { value: '01', label: 'San Pablo' },
    { value: '02', label: 'San Pedro' },
    { value: '03', label: 'San Juan de Mata' },
    { value: '04', label: 'San Luis' },
    { value: '05', label: 'Carara' },
  ],
  '117': [
    { value: '01', label: 'Santa María' },
    { value: '02', label: 'Jardín' },
    { value: '03', label: 'Copey' },
  ],
  '118': [
    { value: '01', label: 'Curridabat' },
    { value: '02', label: 'Granadilla' },
    { value: '03', label: 'Sánchez' },
    { value: '04', label: 'Tirrases' },
  ],
  '119': [
    { value: '01', label: 'San Isidro de El General' },
    { value: '02', label: 'El General' },
    { value: '03', label: 'Daniel Flores' },
    { value: '04', label: 'Rivas' },
    { value: '05', label: 'San Pedro' },
    { value: '06', label: 'Platanares' },
    { value: '07', label: 'Pejibaye' },
    { value: '08', label: 'Cajón' },
    { value: '09', label: 'Barú' },
    { value: '10', label: 'Río Nuevo' },
    { value: '11', label: 'Páramo' },
    { value: '12', label: 'La Amistad' },
  ],
  //   ALAJUELA
  '201': [
    { value: '01', label: 'Alajuela' },
    { value: '02', label: 'San José' },
    { value: '03', label: 'Carrizal' },
    { value: '04', label: 'San Antonio' },
    { value: '05', label: 'Guácima' },
    { value: '06', label: 'San Isidro' },
    { value: '07', label: 'Sabanilla' },
    { value: '08', label: 'San Rafael' },
    { value: '09', label: 'Río Segundo' },
    { value: '10', label: 'Desamparados' },
    { value: '11', label: 'Turrúcares' },
    { value: '12', label: 'Tambor' },
    { value: '13', label: 'Garita' },
    { value: '14', label: 'Sarapiquí' },
  ],
  '202': [
    { value: '01', label: 'San Ramón' },
    { value: '02', label: 'Santiago' },
    { value: '03', label: 'San Juan' },
    { value: '04', label: 'Piedades Norte' },
    { value: '05', label: 'Piedades Sur' },
    { value: '06', label: 'San Rafael' },
    { value: '07', label: 'San Rafael' },
    { value: '08', label: 'San Isidro' },
    { value: '09', label: 'Ángeles' },
    { value: '10', label: 'Alfaro' },
    { value: '11', label: 'Volio' },
    { value: '12', label: 'Concepción' },
    { value: '13', label: 'Zapotal' },
    { value: '14', label: 'Peñas Blancas' },
    { value: '15', label: 'San Lorenzo' },
  ],
  '203': [
    { value: '01', label: 'Grecia' },
    { value: '02', label: 'San Isidro' },
    { value: '03', label: 'San José' },
    { value: '04', label: 'San Roque' },
    { value: '05', label: 'Tacares' },
    { value: '06', label: 'Puente de Piedra' },
    { value: '07', label: 'Bolívar' },
  ],
  '204': [
    { value: '01', label: 'San Mateo' },
    { value: '02', label: 'Desmonte' },
    { value: '03', label: 'Jesús María' },
    { value: '04', label: 'Labrador' },
  ],
  '205': [
    { value: '01', label: 'Atenas' },
    { value: '02', label: 'Jesús' },
    { value: '03', label: 'San Isidro' },
    { value: '04', label: 'Concepción' },
    { value: '05', label: 'San José' },
    { value: '06', label: 'Santa Eulalia' },
    { value: '07', label: 'Escobal' },
  ],
  '206': [
    { value: '01', label: 'Naranjo' },
    { value: '02', label: 'San Miguel' },
    { value: '03', label: 'San José' },
    { value: '04', label: 'Cirrí Sur' },
    { value: '05', label: 'San Jerónimo' },
    { value: '06', label: 'San Juan' },
    { value: '07', label: 'Rosario' },
    { value: '08', label: 'Palmitos' },
  ],
  '207': [
    { value: '01', label: 'Palmares' },
    { value: '02', label: 'Zaragoza' },
    { value: '03', label: 'Buenos Aires' },
    { value: '04', label: 'Santiago' },
    { value: '05', label: 'Candelaria' },
    { value: '06', label: 'Esquipulas' },
    { value: '07', label: 'Granja' },
  ],
  '208': [
    { value: '01', label: 'San Pedro' },
    { value: '02', label: 'San Juan' },
    { value: '03', label: 'San Rafael' },
    { value: '04', label: 'Carrillos' },
    { value: '05', label: 'Sabana Redonda' },
  ],
  '209': [
    { value: '01', label: 'Orotina' },
    { value: '02', label: 'El Mastate' },
    { value: '03', label: 'Hacienda Vieja' },
    { value: '04', label: 'Coyolar' },
    { value: '05', label: 'Ceiba' },
  ],
  '210': [
    { value: '01', label: 'Quesada' },
    { value: '02', label: 'Florencia' },
    { value: '03', label: 'Buenavista' },
    { value: '04', label: 'Aguas Zarcas' },
    { value: '05', label: 'Venecia' },
    { value: '06', label: 'Pital' },
    { value: '07', label: 'Fortuna' },
    { value: '08', label: 'Tigra' },
    { value: '09', label: 'Palmera' },
    { value: '10', label: 'Venado' },
    { value: '11', label: 'Cutris' },
    { value: '12', label: 'Monterrey' },
    { value: '13', label: 'Pocosol' },
  ],
  '211': [
    { value: '01', label: 'Zarcero' },
    { value: '02', label: 'Laguna' },
    { value: '03', label: 'Tapezco' },
    { value: '04', label: 'Guadalupe' },
    { value: '05', label: 'Palmira' },
    { value: '06', label: 'Zapote' },
    { value: '07', label: 'Brisas' },
  ],
  '212': [
    { value: '01', label: 'Sarchí Norte' },
    { value: '02', label: 'Sarchí Sur' },
    { value: '03', label: 'Toro Amarillo' },
    { value: '04', label: 'San Pedro' },
    { value: '05', label: 'Rodríguez' },
  ],
  '213': [
    { value: '01', label: 'Upala' },
    { value: '02', label: 'Aguas Claras' },
    { value: '03', label: 'San José o Pizote' },
    { value: '04', label: 'Bijagua' },
    { value: '05', label: 'Delicias' },
    { value: '06', label: 'Dos Ríos' },
    { value: '07', label: 'Yolillal' },
    { value: '08', label: 'Canalete' },
  ],
  '214': [
    { value: '01', label: 'Los Chiles' },
    { value: '02', label: 'Caño Negro' },
    { value: '03', label: 'El Amparo' },
    { value: '04', label: 'San Jorge' },
  ],
  '215': [
    { value: '01', label: 'San Rafael' },
    { value: '02', label: 'Buenavista' },
    { value: '03', label: 'Cote' },
    { value: '04', label: 'Katira' },
  ],
  '216': [
    { value: '01', label: 'Río Cuarto' },
    { value: '02', label: 'Santa Rita' },
    { value: '03', label: 'Santa Isabel' },
  ],
  //   CARTAGO
  '301': [
    { value: '01', label: 'Oriental' },
    { value: '02', label: 'Occidental' },
    { value: '03', label: 'Carmen' },
    { value: '04', label: 'San Nicolás' },
    { value: '05', label: 'Aguacaliente o San Francisco' },
    { value: '06', label: 'Guadalupe o Arenilla' },
    { value: '07', label: 'Corralillo' },
    { value: '08', label: 'Tierra Blanca' },
    { value: '09', label: 'Dulce Nombre' },
    { value: '10', label: 'Llano Grande' },
    { value: '11', label: 'Quebradilla' },
  ],
  '302': [
    { value: '01', label: 'Paraíso' },
    { value: '02', label: 'Santiago' },
    { value: '03', label: 'Orosi' },
    { value: '04', label: 'Cachí' },
    { value: '05', label: 'Llanos de Santa Lucía' },
  ],
  '303': [
    { value: '01', label: 'Tres Ríos' },
    { value: '02', label: 'San Diego' },
    { value: '03', label: 'San Juan' },
    { value: '04', label: 'San Rafael' },
    { value: '05', label: 'Concepción' },
    { value: '06', label: 'Dulce Nombre' },
    { value: '07', label: 'San Ramón' },
    { value: '08', label: 'Río Azul' },
  ],
  '304': [
    { value: '01', label: 'Juan Viñas' },
    { value: '02', label: 'Tucurrique' },
    { value: '03', label: 'Pejibaye' },
  ],
  '305': [
    { value: '01', label: 'Turrialba' },
    { value: '02', label: 'La Suiza' },
    { value: '03', label: 'Peralta' },
    { value: '04', label: 'Santa Cruz' },
    { value: '05', label: 'Santa Teresita' },
    { value: '06', label: 'Pavones' },
    { value: '07', label: 'Tuis' },
    { value: '08', label: 'Tayutic' },
    { value: '09', label: 'Santa Rosa' },
    { value: '10', label: 'Tres Equis' },
    { value: '11', label: 'La Isabel' },
    { value: '12', label: 'Chirripó' },
  ],
  '306': [
    { value: '01', label: 'Pacayas' },
    { value: '02', label: 'Cervantes' },
    { value: '03', label: 'Capellades' },
  ],
  '307': [
    { value: '01', label: 'San Rafael' },
    { value: '02', label: 'Cot' },
    { value: '03', label: 'Potrero Cerrado' },
    { value: '04', label: 'Cipreses' },
    { value: '05', label: 'Santa Rosa' },
  ],
  '308': [
    { value: '01', label: 'El Tejar' },
    { value: '02', label: 'San Isidro' },
    { value: '03', label: 'Tobosi' },
    { value: '04', label: 'Patio de Agua' },
  ],
  //   HEREDIA
  '401': [
    { value: '01', label: 'Heredia' },
    { value: '02', label: 'Mercedes' },
    { value: '03', label: 'San Francisco' },
    { value: '04', label: 'Ulloa' },
    { value: '05', label: 'Vara Blanca' },
  ],
  '402': [
    { value: '01', label: 'Barva' },
    { value: '02', label: 'San Pedro' },
    { value: '03', label: 'San Pablo' },
    { value: '04', label: 'San Roque' },
    { value: '05', label: 'Santa Lucía' },
    { value: '06', label: 'San José de la Montaña' },
  ],
  '403': [
    { value: '01', label: 'Santo Domingo' },
    { value: '02', label: 'San Vicente' },
    { value: '03', label: 'San Miguel' },
    { value: '04', label: 'Paracito' },
    { value: '05', label: 'Santo Tomás' },
    { value: '06', label: 'Santa Rosa' },
    { value: '07', label: 'Tures' },
    { value: '08', label: 'Pará' },
  ],
  '404': [
    { value: '01', label: 'Santa Bárbara' },
    { value: '02', label: 'San Pedro' },
    { value: '03', label: 'San Juan' },
    { value: '04', label: 'Jesús' },
    { value: '05', label: 'Santo Domingo' },
    { value: '06', label: 'Purabá' },
  ],
  '405': [
    { value: '01', label: 'San Rafael' },
    { value: '02', label: 'San Josecito' },
    { value: '03', label: 'Santiago' },
    { value: '04', label: 'Ángeles' },
    { value: '05', label: 'Concepción' },
  ],
  '406': [
    { value: '01', label: 'San Isidro' },
    { value: '02', label: 'San José' },
    { value: '03', label: 'Concepción' },
    { value: '04', label: 'San Francisco' },
  ],
  '407': [
    { value: '01', label: 'San Antonio' },
    { value: '02', label: 'La Ribera' },
    { value: '03', label: 'Asunción' },
  ],
  '408': [
    { value: '01', label: 'San Joaquín' },
    { value: '02', label: 'Barrantes' },
    { value: '03', label: 'Llorente' },
  ],
  '409': [
    { value: '01', label: 'San Pablo' },
    { value: '02', label: 'Rincón de Sabanilla' },
  ],
  '410': [
    { value: '01', label: 'Puerto Viejo' },
    { value: '02', label: 'La Virgen' },
    { value: '03', label: 'Horquetas' },
    { value: '04', label: 'Llanuras del Gaspar' },
    { value: '05', label: 'Cureña' },
  ],
  //   GUANACASTE
  '501': [
    { value: '01', label: 'Liberia' },
    { value: '02', label: 'Cañas Dulces' },
    { value: '03', label: 'Mayorga' },
    { value: '04', label: 'Nacascolo' },
    { value: '05', label: 'Curubandé' },
  ],
  '502': [
    { value: '01', label: 'Nicoya' },
    { value: '02', label: 'Mansión' },
    { value: '03', label: 'San Antonio' },
    { value: '04', label: 'Quebrada Honda' },
    { value: '05', label: 'Sámara' },
    { value: '06', label: 'Nosara' },
    { value: '07', label: 'Belén de Nosarita' },
  ],
  '503': [
    { value: '01', label: 'Santa Cruz' },
    { value: '02', label: 'Bolsón' },
    { value: '03', label: 'Veintisiete de Abril' },
    { value: '04', label: 'Tempate' },
    { value: '05', label: 'Cartagena' },
    { value: '06', label: 'Cuajiniquil' },
    { value: '07', label: 'Diriá' },
    { value: '08', label: 'Cabo Velas' },
    { value: '09', label: 'Tamarindo' },
  ],
  '504': [
    { value: '01', label: 'Bagaces' },
    { value: '02', label: 'Fortuna' },
    { value: '03', label: 'Mogote' },
    { value: '04', label: 'Río Naranjo' },
  ],
  '505': [
    { value: '01', label: 'Filadelfia' },
    { value: '02', label: 'Palmira' },
    { value: '03', label: 'Sardinal' },
    { value: '04', label: 'Belén' },
  ],
  '506': [
    { value: '01', label: 'Cañas' },
    { value: '02', label: 'Palmira' },
    { value: '03', label: 'San Miguel' },
    { value: '04', label: 'Bebedero' },
    { value: '05', label: 'Porozal' },
  ],
  '507': [
    { value: '01', label: 'Las Juntas' },
    { value: '02', label: 'Sierra' },
    { value: '03', label: 'San Juan' },
    { value: '04', label: 'Colorado' },
  ],
  '508': [
    { value: '01', label: 'Tilarán' },
    { value: '02', label: 'Quebrada Grande' },
    { value: '03', label: 'Tronadora' },
    { value: '04', label: 'Santa Rosa' },
    { value: '05', label: 'Líbano' },
    { value: '06', label: 'Tierras Morenas' },
    { value: '07', label: 'Arenal' },
    { value: '08', label: 'Cabeceras' },
  ],
  '509': [
    { value: '01', label: 'Carmona' },
    { value: '02', label: 'Santa Rita' },
    { value: '03', label: 'Zapotal' },
    { value: '04', label: 'San Pablo' },
    { value: '05', label: 'Porvenir' },
    { value: '06', label: 'Bejuco' },
  ],
  '510': [
    { value: '01', label: 'La Cruz' },
    { value: '02', label: 'Santa Cecilia' },
    { value: '03', label: 'La Garita' },
    { value: '04', label: 'Santa Elena' },
  ],
  '511': [
    { value: '01', label: 'Hojancha' },
    { value: '02', label: 'Monte Romo' },
    { value: '03', label: 'Puerto Carrillo' },
    { value: '04', label: 'Huacas' },
    { value: '05', label: 'Matambú' },
  ],
  //   PUNTARENAS
  '601': [
    { value: '01', label: 'Puntarenas' },
    { value: '02', label: 'Pitahaya' },
    { value: '03', label: 'Chomes' },
    { value: '04', label: 'Lepanto' },
    { value: '05', label: 'Paquera' },
    { value: '07', label: 'Guacimal' },
    { value: '08', label: 'Barranca' },
    { value: '09', label: 'Monte Verde' },
    { value: '11', label: 'Cóbano' },
    { value: '12', label: 'Chacarita' },
    { value: '13', label: 'Chira' },
    { value: '14', label: 'Acapulco' },
    { value: '15', label: 'El Roble' },
    { value: '16', label: 'Arancibia' },
  ],
  '602': [
    { value: '01', label: 'Espíritu Santo' },
    { value: '02', label: 'San Juan Grande' },
    { value: '03', label: 'Macacona' },
    { value: '04', label: 'San Rafael' },
    { value: '05', label: 'San Jerónimo' },
    { value: '06', label: 'Caldera' },
  ],
  '603': [
    { value: '01', label: 'Buenos Aires' },
    { value: '02', label: 'Volcán' },
    { value: '03', label: 'Potrero Grande' },
    { value: '04', label: 'Boruca' },
    { value: '05', label: 'Pilas' },
    { value: '06', label: 'Colinas' },
    { value: '07', label: 'Chánguena' },
    { value: '08', label: 'Biolley' },
    { value: '09', label: 'Brunka' },
  ],
  '604': [
    { value: '01', label: 'Miramar' },
    { value: '02', label: 'La Unión' },
    { value: '03', label: 'San Isidro' },
  ],
  '605': [
    { value: '01', label: 'Puerto Cortés' },
    { value: '02', label: 'Palmar' },
    { value: '03', label: 'Sierpe' },
    { value: '04', label: 'Bahía Ballena' },
    { value: '05', label: 'Piedras Blancas' },
    { value: '06', label: 'Bahía Drake' },
  ],
  '606': [
    { value: '01', label: 'Quepos' },
    { value: '02', label: 'Savegre' },
    { value: '03', label: 'Naranjito' },
  ],
  '607': [
    { value: '01', label: 'Golfito' },
    { value: '02', label: 'Puerto Jiménez' },
    { value: '03', label: 'Guaycará' },
    { value: '04', label: 'Pavón' },
  ],
  '608': [
    { value: '01', label: 'San Vito' },
    { value: '02', label: 'Sabalito' },
    { value: '03', label: 'Aguabuena' },
    { value: '04', label: 'Limoncito' },
    { value: '05', label: 'Pittier' },
    { value: '06', label: 'Gutiérrez Braun' },
  ],
  '609': [{ value: '01', label: 'Parrita' }],
  '610': [
    { value: '01', label: 'Corredor' },
    { value: '02', label: 'La Cuesta' },
    { value: '03', label: 'Canoas' },
    { value: '04', label: 'Laurel' },
  ],
  '611': [
    { value: '01', label: 'Jacó' },
    { value: '02', label: 'Tárcoles' },
  ],
  //   LIMÓN

  '701': [
    { value: '01', label: 'Limón' },
    { value: '02', label: 'Valle La Estrella' },
    { value: '03', label: 'Río Blanco' },
    { value: '04', label: 'Matama' },
  ],
  '702': [
    { value: '01', label: 'Guápiles' },
    { value: '02', label: 'Jiménez' },
    { value: '03', label: 'Rita' },
    { value: '04', label: 'Roxana' },
    { value: '05', label: 'Cariari' },
    { value: '06', label: 'Colorado' },
    { value: '07', label: 'La Colonia' },
  ],
  '703': [
    { value: '01', label: 'Siquirres' },
    { value: '02', label: 'Pacuarito' },
    { value: '03', label: 'Florida' },
    { value: '04', label: 'Germania' },
    { value: '05', label: 'El Cairo' },
    { value: '06', label: 'Alegría' },
    { value: '07', label: 'Reventazón' },
  ],
  '704': [
    { value: '01', label: 'Bratsi' },
    { value: '02', label: 'Sixaola' },
    { value: '03', label: 'Cahuita' },
    { value: '04', label: 'Telire' },
  ],
  '705': [
    { value: '01', label: 'Matina' },
    { value: '02', label: 'Batán' },
    { value: '03', label: 'Carrandi' },
  ],
  '706': [
    { value: '01', label: 'Guácimo' },
    { value: '02', label: 'Mercedes' },
    { value: '03', label: 'Pocora' },
    { value: '04', label: 'Río Jiménez' },
    { value: '05', label: 'Duacarí' },
  ],
}
